{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gtd.b2b2c",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 12527665,
          "sha512": "294321306c62cd94c717e2c615410c51c766f9512f75efbbce78b3eac34aeac6e0abf09e795fd39aa213fd4fe756eefa9161227d6e92c601c2f7fc704c558f76",
          "sha256": "41eac1661eb532691c841611ecff34a88b626af945391badb9e4894af47b40c1",
          "sha1": "7519119af3e5b10d54d1faf63f8633fc8d3d3265",
          "md5": "45994e4abfb45f43c17a963803d28942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 12527665,
          "sha512": "294321306c62cd94c717e2c615410c51c766f9512f75efbbce78b3eac34aeac6e0abf09e795fd39aa213fd4fe756eefa9161227d6e92c601c2f7fc704c558f76",
          "sha256": "41eac1661eb532691c841611ecff34a88b626af945391badb9e4894af47b40c1",
          "sha1": "7519119af3e5b10d54d1faf63f8633fc8d3d3265",
          "md5": "45994e4abfb45f43c17a963803d28942"
        }
      ]
    }
  ]
}
