{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12431,
          "sha512": "ad884a1ceada3c3bca06d7ccb2a5ca82fe17f5e4db2c22f14c18a454285d931956e7a1b9d5d85fded29006acfef8e3b08b68d208c1e9b4d1576730899f310865",
          "sha256": "cc95f50e5d3b898a3e381ce48522a282ab6d14a47b0221cd4a18d52eea29c68f",
          "sha1": "368ae5d8eb76fc982bbbe349d9600f0811af4407",
          "md5": "13cd7f594f26707d1f9ead30a0f3db42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12431,
          "sha512": "ad884a1ceada3c3bca06d7ccb2a5ca82fe17f5e4db2c22f14c18a454285d931956e7a1b9d5d85fded29006acfef8e3b08b68d208c1e9b4d1576730899f310865",
          "sha256": "cc95f50e5d3b898a3e381ce48522a282ab6d14a47b0221cd4a18d52eea29c68f",
          "sha1": "368ae5d8eb76fc982bbbe349d9600f0811af4407",
          "md5": "13cd7f594f26707d1f9ead30a0f3db42"
        }
      ]
    }
  ]
}
