{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 13188,
          "sha512": "39c00ed5cc97c098081b7d3e86be482f7e84ffb5716b9f7e46deb7b0c3c041f5db13d0450bc9e76936279f01ad2bb639c6c003f7dad3bfa86cd2372c3c7de688",
          "sha256": "af8ad63d9423980a9033590f5474faeac0bcd909cd81d0e274a81adf6f73e335",
          "sha1": "3c6833ade665fe505bf31b87377f4429da8caaf0",
          "md5": "ae7e22195726c8f2e3d7714933be960f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 13188,
          "sha512": "39c00ed5cc97c098081b7d3e86be482f7e84ffb5716b9f7e46deb7b0c3c041f5db13d0450bc9e76936279f01ad2bb639c6c003f7dad3bfa86cd2372c3c7de688",
          "sha256": "af8ad63d9423980a9033590f5474faeac0bcd909cd81d0e274a81adf6f73e335",
          "sha1": "3c6833ade665fe505bf31b87377f4429da8caaf0",
          "md5": "ae7e22195726c8f2e3d7714933be960f"
        }
      ]
    }
  ]
}
