{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 15054,
          "sha512": "33971b08b922f28917839db0da239449391d1c06e55a8bfb7abc1c2d86b3664c9e8d4f6b1bc910045d725eb92feac757f630d17b0e2b6bfb2ca6026e1cf7bf45",
          "sha256": "e9817a08e0be4d48080cb42b0529d8f53b85cea12bed662529d01f14a145f2ad",
          "sha1": "06e9bb20601a7c6b977002b1ef4a079ce14f1947",
          "md5": "da00edbcf18ec8e9aafbad50858a0bd1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 15054,
          "sha512": "33971b08b922f28917839db0da239449391d1c06e55a8bfb7abc1c2d86b3664c9e8d4f6b1bc910045d725eb92feac757f630d17b0e2b6bfb2ca6026e1cf7bf45",
          "sha256": "e9817a08e0be4d48080cb42b0529d8f53b85cea12bed662529d01f14a145f2ad",
          "sha1": "06e9bb20601a7c6b977002b1ef4a079ce14f1947",
          "md5": "da00edbcf18ec8e9aafbad50858a0bd1"
        }
      ]
    }
  ]
}
