{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12429,
          "sha512": "45598bf5d031dbcf924c2f65c901f5bdc08007b302baf3fce7e60ef5257b6bfb9da8252df59974635012ecb17dc23c391682a0ec868d67a8219fc9c55b65765d",
          "sha256": "b5a96740d135111d12bbbbc283beab26ddefa4fdc170a12df80b8a815deafd56",
          "sha1": "d917ee98e2eca89d5490667e435deb93add64d1e",
          "md5": "3c71cd4000fae25050e4f387b9b4f40d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12429,
          "sha512": "45598bf5d031dbcf924c2f65c901f5bdc08007b302baf3fce7e60ef5257b6bfb9da8252df59974635012ecb17dc23c391682a0ec868d67a8219fc9c55b65765d",
          "sha256": "b5a96740d135111d12bbbbc283beab26ddefa4fdc170a12df80b8a815deafd56",
          "sha1": "d917ee98e2eca89d5490667e435deb93add64d1e",
          "md5": "3c71cd4000fae25050e4f387b9b4f40d"
        }
      ]
    }
  ]
}
