{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12492,
          "sha512": "34312c0a03eef133f1c7ba7847bf80bd26d515aa58e3da23a4ce2b243a0406890e14e62e561069417fd2cad7b296c13bf6bbb3368c999c3114a54258205bf9fe",
          "sha256": "4946809511ffd43d95e33787a2421564d363fab6f7c4649888dc7df47ebe29b0",
          "sha1": "4accc72fb56a77cadf8a7a1d612f064fd88e52a2",
          "md5": "a733695296eb80527a11164fc4203b57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12492,
          "sha512": "34312c0a03eef133f1c7ba7847bf80bd26d515aa58e3da23a4ce2b243a0406890e14e62e561069417fd2cad7b296c13bf6bbb3368c999c3114a54258205bf9fe",
          "sha256": "4946809511ffd43d95e33787a2421564d363fab6f7c4649888dc7df47ebe29b0",
          "sha1": "4accc72fb56a77cadf8a7a1d612f064fd88e52a2",
          "md5": "a733695296eb80527a11164fc4203b57"
        }
      ]
    }
  ]
}
