{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12565,
          "sha512": "c50a18d0b320734c693f0f1c25f82548952b51100fa59257e4dd13cb9ee3c638e11fb80a8ecb45984e09bd6d2f5b1f2f186235c4d4593a994311a104b12a04dc",
          "sha256": "7397372237f9d3bf24c40bf5a11a98df4c2fa08942f304150641f91007d0c46c",
          "sha1": "bb61fc24ebd7c4e79720ea604e658d6c2ec70483",
          "md5": "9f187b23ab7a959784182241778b843a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12565,
          "sha512": "c50a18d0b320734c693f0f1c25f82548952b51100fa59257e4dd13cb9ee3c638e11fb80a8ecb45984e09bd6d2f5b1f2f186235c4d4593a994311a104b12a04dc",
          "sha256": "7397372237f9d3bf24c40bf5a11a98df4c2fa08942f304150641f91007d0c46c",
          "sha1": "bb61fc24ebd7c4e79720ea604e658d6c2ec70483",
          "md5": "9f187b23ab7a959784182241778b843a"
        }
      ]
    }
  ]
}
