{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 15052,
          "sha512": "30ba37730f2a147d289e53f546a32e2757684fd8d3b5f259241dd0daf9045d5fa9a604f59b19506c8a623c2b65a9bf4a91c2d55bcc404f2194891e64f4d5759f",
          "sha256": "0528bc99b482faeed11c5548d6cd71f419aa5b7d961daf3efbcb9f35a73f271c",
          "sha1": "e9c5aacd48eecd5cd35356fff19d3cfd143c4a66",
          "md5": "c237571ca59259de2880157978c050da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 15052,
          "sha512": "30ba37730f2a147d289e53f546a32e2757684fd8d3b5f259241dd0daf9045d5fa9a604f59b19506c8a623c2b65a9bf4a91c2d55bcc404f2194891e64f4d5759f",
          "sha256": "0528bc99b482faeed11c5548d6cd71f419aa5b7d961daf3efbcb9f35a73f271c",
          "sha1": "e9c5aacd48eecd5cd35356fff19d3cfd143c4a66",
          "md5": "c237571ca59259de2880157978c050da"
        }
      ]
    }
  ]
}
