{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 15130,
          "sha512": "5d3a8fb2f98435498659d57470390b43aef8973ee7d4a72c5fbb00158dad935f66876f895e055aaf3b7d77809c06870a172ae0b6112cca6cbd2ac3462aae8a7a",
          "sha256": "be3481e4d397fc2ae8a1080f336c7e73639bfcd684e27ad1f7e890251c74db56",
          "sha1": "6f1c1c0e3002f648b19af5fdbba8497af328e385",
          "md5": "e973f62d18496efa63b06bdfd5831b21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 15130,
          "sha512": "5d3a8fb2f98435498659d57470390b43aef8973ee7d4a72c5fbb00158dad935f66876f895e055aaf3b7d77809c06870a172ae0b6112cca6cbd2ac3462aae8a7a",
          "sha256": "be3481e4d397fc2ae8a1080f336c7e73639bfcd684e27ad1f7e890251c74db56",
          "sha1": "6f1c1c0e3002f648b19af5fdbba8497af328e385",
          "md5": "e973f62d18496efa63b06bdfd5831b21"
        }
      ]
    }
  ]
}
